/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/SQSWpo1c4eB6mhQn/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#6142a4']} />
      <group {...props} dispose={null}>
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={materials['Floor Material']}
          castShadow
          receiveShadow
          position={[-348.7, -260, -305]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={1}
        />
        <mesh
          name="Light switch"
          geometry={nodes['Light switch'].geometry}
          material={materials['Light switch Material']}
          castShadow
          receiveShadow
          position={[-300, 85, 235.32]}
        />
        <group name="Cat" position={[-414.81, 269.86, 35.06]} rotation={[-Math.PI, -Math.PI / 4, -Math.PI]} scale={1}>
          <group name="Body" position={[0, 0.02, 4.61]} rotation={[-Math.PI, 0, Math.PI]} scale={1}>
            <mesh
              name="Tail"
              geometry={nodes.Tail.geometry}
              material={materials['Tail Material']}
              castShadow
              receiveShadow
              position={[-7.77, -20.82, -23.43]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={0.29}
            />
            <group name="Hair" position={[9.04, 12.31, 12.89]} scale={0.15}>
              <group name="Hair Right" position={[145.09, 0, 5.91]} rotation={[-Math.PI, 0, -Math.PI]} scale={1}>
                <mesh
                  name="hair 3"
                  geometry={nodes['hair 3'].geometry}
                  material={materials['hair 3 Material']}
                  position={[3.95, -18.89, 0]}
                  rotation={[0, 0, 0.33]}
                  scale={1}
                />
                <mesh
                  name="hair 2"
                  geometry={nodes['hair 2'].geometry}
                  material={materials['hair 2 Material']}
                  position={[-3.27, 2.06, 0]}
                  rotation={[0, 0, 0.33]}
                  scale={1}
                />
                <mesh
                  name="hair"
                  geometry={nodes.hair.geometry}
                  material={materials['hair Material']}
                  position={[-3.27, 26.12, 0]}
                />
              </group>
              <group name="Hair Left" position={[-145.09, 0, -5.91]}>
                <mesh
                  name="hair 31"
                  geometry={nodes['hair 31'].geometry}
                  material={materials['hair 31 Material']}
                  position={[3.95, -18.89, 0]}
                  rotation={[0, 0, 0.33]}
                  scale={1}
                />
                <mesh
                  name="hair 21"
                  geometry={nodes['hair 21'].geometry}
                  material={materials['hair 21 Material']}
                  position={[-3.27, 2.06, 0]}
                  rotation={[0, 0, 0.33]}
                  scale={1}
                />
                <mesh
                  name="hair1"
                  geometry={nodes.hair1.geometry}
                  material={materials['hair1 Material']}
                  position={[-3.27, 26.12, 0]}
                />
              </group>
            </group>
            <group name="Arms" position={[8.66, -6.23, 16.39]} scale={0.5}>
              <mesh
                name="Right Arm"
                geometry={nodes['Right Arm'].geometry}
                material={materials['Right Arm Material']}
                castShadow
                receiveShadow
                position={[24.89, -6.65, 13.87]}
                rotation={[1.24, 0.86, 0.42]}
                scale={1.19}
              />
              <mesh
                name="Left Arm"
                geometry={nodes['Left Arm'].geometry}
                material={materials['Left Arm Material']}
                castShadow
                receiveShadow
                position={[-22.24, -6.65, 13.87]}
                rotation={[1.24, -0.86, -0.42]}
                scale={1.19}
              />
            </group>
            <group name="Ears" position={[10.83, 27.1, 1.62]} scale={0.5}>
              <group name=" Left Ear" position={[-35.19, 2.24, 0]} rotation={[0, 0, Math.PI / 2]} scale={0.58}>
                <mesh
                  name="ear"
                  geometry={nodes.ear.geometry}
                  material={materials['ear Material']}
                  position={[-18.46, 7.98, 9.59]}
                  rotation={[-0.02, 0.01, 0.14]}
                  scale={3.02}
                />
                <mesh
                  name="ear1"
                  geometry={nodes.ear1.geometry}
                  material={materials['ear1 Material']}
                  position={[-3.46, -8.84, 11.7]}
                  rotation={[0, 0, 0.63]}
                  scale={2.69}
                />
              </group>
              <group name="Right Ear" position={[35.5, -0.44, 0]} scale={0.58}>
                <mesh
                  name="ear2"
                  geometry={nodes.ear2.geometry}
                  material={materials['ear2 Material']}
                  position={[-18.46, 7.98, 9.59]}
                  rotation={[-0.02, 0.01, 0.14]}
                  scale={3.02}
                />
                <mesh
                  name="ear3"
                  geometry={nodes.ear3.geometry}
                  material={materials['ear3 Material']}
                  position={[-3.46, -8.84, 11.7]}
                  rotation={[0, 0, 0.63]}
                  scale={2.69}
                />
              </group>
            </group>
            <mesh
              name="Body1"
              geometry={nodes.Body1.geometry}
              material={materials['Body1 Material']}
              castShadow
              position={[10.23, -1.02, -2.13]}
              scale={0.15}
            />
            <group name="Nose" position={[11.58, 15.03, 23.22]} rotation={[-0.4, 0.01, -0.04]} scale={0.08}>
              <mesh
                name="Cylinder"
                geometry={nodes.Cylinder.geometry}
                material={materials['Cylinder Material']}
                position={[-22, 21, 8]}
                rotation={[0, -0.02, 0.08]}
                scale={1}
              />
              <mesh
                name="Torus 2"
                geometry={nodes['Torus 2'].geometry}
                material={materials['Torus 2 Material']}
                position={[-47.51, 17.38, 0]}
                rotation={[0, -0.02, 2.2]}
                scale={1}
              />
              <mesh
                name="Torus"
                geometry={nodes.Torus.geometry}
                material={materials['Torus Material']}
                position={[-1.89, 20.99, 0.87]}
                rotation={[0, -0.02, 2.2]}
                scale={1}
              />
            </group>
            <group name="Eyes" position={[10.03, 15.95, 18.9]} scale={0.5}>
              <mesh
                name="Right Eye"
                geometry={nodes['Right Eye'].geometry}
                material={materials['Right Eye Material']}
                position={[21.32, 0.19, 0]}
                rotation={[0, 0, 0.09]}
                scale={0.3}
              />
              <mesh
                name="Left Eye"
                geometry={nodes['Left Eye'].geometry}
                material={materials['Left Eye Material']}
                position={[-21.32, -0.19, 0]}
                rotation={[0, 0, 0.09]}
                scale={0.3}
              />
            </group>
            <group name="Feet" position={[9.18, -25.32, 4.62]} scale={0.5}>
              <mesh
                name="Foot 1"
                geometry={nodes['Foot 1'].geometry}
                material={materials['Foot 1 Material']}
                castShadow
                position={[22, 0, 10]}
                rotation={[0, 0, 0]}
                scale={0.3}
              />
              <mesh
                name="Foot"
                geometry={nodes.Foot.geometry}
                material={materials['Foot Material']}
                castShadow
                position={[-20, 0, -20]}
                rotation={[0, 0, 0]}
                scale={0.3}
              />
            </group>
          </group>
        </group>
        <directionalLight
          name="Ambient Light"
          castShadow
          intensity={0.5}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1000}
          shadow-camera-right={1000}
          shadow-camera-top={1000}
          shadow-camera-bottom={-1000}
          position={[681, 977.62, 229]}
        />
        <OrthographicCamera
          name="Isometric Camera"
          makeDefault={true}
          far={100000}
          near={-100000}
          position={[297.61, 743.56, 678.24]}
          rotation={[-0.79, 0.47, 0.43]}
        />
        <group name="Carpet" position={[86, -189, 22]}>
          <mesh
            name="Base"
            geometry={nodes.Base.geometry}
            material={materials['Base Material']}
            castShadow
            receiveShadow
            position={[0, 0, 0]}
          />
          <mesh
            name="Line"
            geometry={nodes.Line.geometry}
            material={materials['Line Material']}
            castShadow
            receiveShadow
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group name="Sliding Door" position={[-258.5, -31.25, -4.5]}>
          <group name="Slide Door 2" position={[-2.5, 0.25, 55.5]}>
            <mesh
              name="Slider Door Frame 2"
              geometry={nodes['Slider Door Frame 2'].geometry}
              material={materials['Slider Door Frame 2 Material']}
              castShadow
              receiveShadow
              position={[2, 0, 0]}
            />
            <mesh
              name="Sliding Door Paper 2"
              geometry={nodes['Sliding Door Paper 2'].geometry}
              material={materials['Sliding Door Paper 2 Material']}
              castShadow
              receiveShadow
              position={[1, -1, 0]}
              rotation={[0, Math.PI / 2, 0]}
            />
          </group>
          <group name="Slide Door 1" position={[2.5, 0.25, 167.5]}>
            <mesh
              name="Sliding Door Frame"
              geometry={nodes['Sliding Door Frame'].geometry}
              material={materials['Sliding Door Frame Material']}
              castShadow
              receiveShadow
              position={[0, 0, -167.5]}
            />
            <mesh
              name="Sliding Door Paper"
              geometry={nodes['Sliding Door Paper'].geometry}
              material={materials['Sliding Door Paper Material']}
              castShadow
              receiveShadow
              position={[-0.5, -1, -167.25]}
            />
          </group>
        </group>
        <group name="Office Room" position={[-481.74, -97.04, -204.69]}>
          <group name="Office Chair" position={[-95, -10, 272]} rotation={[0, Math.PI / 2, 0]} scale={1.58}>
            <mesh
              name="Feet1"
              geometry={nodes.Feet1.geometry}
              material={materials['Feet1 Material']}
              castShadow
              receiveShadow
              position={[0, -37, -5]}
            />
            <mesh
              name="Chair"
              geometry={nodes.Chair.geometry}
              material={materials['Chair Material']}
              castShadow
              receiveShadow
              position={[0, 18, -6]}
            />
          </group>
          <group name="Picture frame" position={[29.74, 127.04, 420.69]} rotation={[0, Math.PI / 2, 0]}>
            <mesh
              name="Rectangle"
              geometry={nodes.Rectangle.geometry}
              material={materials['Rectangle Material']}
              castShadow
              receiveShadow
              position={[3.63, -7.01, -21.5]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Ellipse"
              geometry={nodes.Ellipse.geometry}
              material={materials['Ellipse Material']}
              castShadow
              receiveShadow
              position={[3.63, 8.5, 30.5]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <mesh
              name="Frame"
              geometry={nodes.Frame.geometry}
              material={materials['Frame Material']}
              castShadow
              receiveShadow
              position={[-3, 0, 0]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1}
            />
          </group>
          <group name="iMac" position={[47, 80, 272]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.32}>
            <mesh
              name="Screen"
              geometry={nodes.Screen.geometry}
              material={materials['Screen Material']}
              position={[9, 11, 0]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1}
            />
            <mesh
              name="Hover"
              geometry={nodes.Hover.geometry}
              material={materials['Hover Material']}
              position={[10, 11, 0]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1}
            />
            <mesh
              name="Border"
              geometry={nodes.Border.geometry}
              material={materials['Border Material']}
              position={[8.11, 11, 0]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1}
            />
            <mesh
              name="Monitor"
              geometry={nodes.Monitor.geometry}
              material={materials['Monitor Material']}
              castShadow
              receiveShadow
              position={[0, 0.26, 0]}
              rotation={[0, 0, 0]}
              scale={1}
            />
          </group>
          <group name="Desk" position={[15.74, 25.04, 286.69]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.32}>
            <mesh
              name="Metal"
              geometry={nodes.Metal.geometry}
              material={materials['Metal Material']}
              castShadow
              receiveShadow
              position={[-12.13, -48.8, -1.52]}
              rotation={[Math.PI, 0, -Math.PI]}
              scale={0.76}
            />
            <mesh
              name="Wood"
              geometry={nodes.Wood.geometry}
              material={materials['Wood Material']}
              castShadow
              receiveShadow
              position={[-12.2, -41.89, -0.76]}
              rotation={[-Math.PI, 0, -Math.PI]}
              scale={0.76}
            />
          </group>
        </group>
        <mesh
          name="Wall"
          geometry={nodes.Wall.geometry}
          material={materials['Wall Material']}
          castShadow
          receiveShadow
          position={[-152, 155.75, 54.91]}
        />
        <group name="Second Floor" position={[-451, 206, -5]}>
          <group name="Picture" position={[-178, 150, 291]}>
            <mesh
              name="Picture "
              geometry={nodes['Picture '].geometry}
              material={materials['Picture  Material']}
              castShadow
              receiveShadow
              position={[-2.97, -0.12, -0.16]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1}
            />
            <mesh
              name="Frame1"
              geometry={nodes.Frame1.geometry}
              material={materials['Frame1 Material']}
              castShadow
              receiveShadow
              position={[-3.03, 0.12, 0.16]}
              rotation={[0, Math.PI / 2, 0]}
              scale={1}
            />
          </group>
          <group name="Sakura" position={[6, 125, -196]}>
            <mesh
              name="Sakura1"
              geometry={nodes.Sakura1.geometry}
              material={materials.Sakura}
              position={[6.32, 47.03, 2.06]}
            />
            <mesh
              name="Tree trunk"
              geometry={nodes['Tree trunk'].geometry}
              material={materials['Tree trunk Material']}
              position={[1.33, 28.57, 0.65]}
            />
            <mesh
              name="Rectangle1"
              geometry={nodes.Rectangle1.geometry}
              material={materials['Rectangle1 Material']}
              position={[0.09, 14.22, -0.48]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Pot"
              geometry={nodes.Pot.geometry}
              material={materials['Pot Material']}
              position={[0, 4.09, -0.28]}
            />
          </group>
          <group name="Small Plant " position={[159, 58.85, -193.24]} scale={0.26}>
            <mesh
              name="Leaves"
              geometry={nodes.Leaves.geometry}
              material={materials['Plant Green']}
              castShadow
              receiveShadow
              position={[-571.27, 27, -0.05]}
              scale={3.84}
            />
            <mesh
              name="Pot1"
              geometry={nodes.Pot1.geometry}
              material={materials['Pot1 Material']}
              castShadow
              receiveShadow
              position={[-572.11, -10.1, -1]}
              scale={3.84}
            />
          </group>
          <group name="Lamp-Room1" position={[-135, 30, -155]} scale={0.5}>
            <mesh
              name="Base1"
              geometry={nodes.Base1.geometry}
              material={materials['Base1 Material']}
              castShadow
              position={[0, 23.3, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Wood1"
              geometry={nodes.Wood1.geometry}
              material={materials['Wood1 Material']}
              castShadow
              position={[0, 16.67, 0]}
              scale={2}
            />
          </group>
          <group name="Lamp-Room2" position={[159, 30, -155]} scale={0.5}>
            <mesh
              name="Base2"
              geometry={nodes.Base2.geometry}
              material={materials['Base2 Material']}
              castShadow
              position={[0, 23.3, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Wood2"
              geometry={nodes.Wood2.geometry}
              material={materials['Wood2 Material']}
              castShadow
              position={[0, 16.67, 0]}
              scale={2}
            />
          </group>
          <mesh
            name="Bed Frame"
            geometry={nodes['Bed Frame'].geometry}
            material={materials['Bed Frame Material']}
            castShadow
            receiveShadow
            position={[10, 122, -200.78]}
          />
          <mesh
            name="Paper"
            geometry={nodes.Paper.geometry}
            material={materials['Paper Material']}
            castShadow
            receiveShadow
            position={[12, 224.5, -180.93]}
          />
          <group name="Nightstand 1" position={[160, -12, -173]} scale={1.55}>
            <group name="Drawer 1" position={[0, 21, 4.25]} scale={0.65}>
              <mesh
                name="Cover 1"
                geometry={nodes['Cover 1'].geometry}
                material={materials['Cover 1 Material']}
                position={[0, -16, 32]}
              />
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials.Drawer}
                castShadow
                receiveShadow
                position={[0, -17, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1.55}
              />
            </group>
            <group name=" Drawer2" position={[0, -0.45, 4.25]} scale={0.65}>
              <mesh
                name="Cover 2"
                geometry={nodes['Cover 2'].geometry}
                material={materials['Cover 2 Material']}
                position={[0, -16, 32]}
              />
              <mesh
                name="Cube 2"
                geometry={nodes['Cube 2'].geometry}
                material={materials.Drawer}
                castShadow
                receiveShadow
                position={[0, -16, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1.55}
              />
            </group>
            <mesh
              name="Nightstands"
              geometry={nodes.Nightstands.geometry}
              material={materials['Nightstands Material']}
              castShadow
              receiveShadow
              position={[-94.96, -1.55, -1.17]}
              scale={0.65}
            />
          </group>
          <group name="Nightstand 2" position={[-134, -12, -173]} scale={1.55}>
            <group name="Drawer 11" position={[0.06, 10, 4.25]} scale={0.65}>
              <mesh
                name="Cover 11"
                geometry={nodes['Cover 11'].geometry}
                material={materials['Cover 11 Material']}
                castShadow
                receiveShadow
                position={[-0.1, 0, 32.12]}
              />
              <mesh
                name="Cube1"
                geometry={nodes.Cube1.geometry}
                material={materials.Drawer}
                castShadow
                receiveShadow
                position={[0, 0, -0.39]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1.55}
              />
            </group>
            <group name="Drawer 2" position={[0.06, -10.96, 4.25]} scale={0.65}>
              <mesh
                name="Cover 21"
                geometry={nodes['Cover 21'].geometry}
                material={materials['Cover 21 Material']}
                castShadow
                receiveShadow
                position={[0, 0, 32]}
              />
              <mesh
                name="Cube2"
                geometry={nodes.Cube2.geometry}
                material={materials.Drawer}
                castShadow
                receiveShadow
                position={[0, 0.08, -0.39]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={1.55}
              />
            </group>
          </group>
          <mesh
            name="Second Floor Wood"
            geometry={nodes['Second Floor Wood'].geometry}
            material={materials['Second Floor Wood Material']}
            castShadow
            receiveShadow
            position={[0, -47.84, 0]}
            scale={1}
          />
        </group>
        <group
          name="Furnitures"
          position={[85.35, -98.03, 205.06]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.86, 0.97, 0.86]}
        >
          <mesh
            name="Furnitures1"
            geometry={nodes.Furnitures1.geometry}
            material={materials['Furnitures1 Material']}
            receiveShadow
            position={[291.88, 139.45, 219.21]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[1.16, 1.03, 1.16]}
          />
          <mesh
            name="Metal1"
            geometry={nodes.Metal1.geometry}
            material={materials['Metal1 Material']}
            castShadow
            receiveShadow
            position={[62.7, -60.06, 111.64]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[1.16, 1.03, 1.16]}
          />
        </group>
        <group name="TV Stand" position={[50, -135, -202]}>
          <group name="Drawer 3" position={[80.52, 0, -8.7]}>
            <mesh
              name="Cover 3"
              geometry={nodes['Cover 3'].geometry}
              material={materials['Cover 3 Material']}
              position={[2.01, 0, 28.41]}
              scale={[1, 1, 3.99]}
            />
            <mesh
              name="Cube3"
              geometry={nodes.Cube3.geometry}
              material={materials.Drawer}
              castShadow
              receiveShadow
              position={[0, 0, 10.56]}
            />
          </group>
          <group name="Drawer 21" position={[0.56, 0, -8.7]}>
            <mesh
              name="Cover 22"
              geometry={nodes['Cover 22'].geometry}
              material={materials['Cover 22 Material']}
              position={[0, 0, 28.41]}
              scale={[1, 1, 3.99]}
            />
            <mesh
              name="Cube4"
              geometry={nodes.Cube4.geometry}
              material={materials.Drawer}
              castShadow
              receiveShadow
              position={[0, 0, 10.56]}
            />
          </group>
          <group name="Drawer 12" position={[-78.52, 0, -8.7]}>
            <mesh
              name="Cover 12"
              geometry={nodes['Cover 12'].geometry}
              material={materials['Cover 12 Material']}
              position={[-2, 0, 28.41]}
              scale={[1, 1, 3.99]}
            />
            <mesh
              name="Cube5"
              geometry={nodes.Cube5.geometry}
              material={materials.Drawer}
              castShadow
              receiveShadow
              position={[0, 0, 10.56]}
            />
          </group>
        </group>
        <group
          name="Table"
          position={[86.68, -139.13, 15.93]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.83, 0.41, 0.58]}
        >
          <mesh
            name="Metal2"
            geometry={nodes.Metal2.geometry}
            material={materials['Metal2 Material']}
            castShadow
            receiveShadow
            position={[0.59, -44.29, -0.26]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1.74, 2.45, 1.21]}
          />
          <mesh
            name="Base3"
            geometry={nodes.Base3.geometry}
            material={materials['Base3 Material']}
            castShadow
            receiveShadow
            position={[0, -79.22, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Glass"
            geometry={nodes.Glass.geometry}
            material={materials['Glass Material']}
            castShadow
            receiveShadow
            position={[0, 32.69, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <group name="Lamp Living Room" position={[299.46, -97, 209]}>
          <mesh
            name="Paper1"
            geometry={nodes.Paper1.geometry}
            material={materials['Paper1 Material']}
            castShadow
            receiveShadow
            position={[0, 34, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Wood3"
            geometry={nodes.Wood3.geometry}
            material={materials['Wood3 Material']}
            castShadow
            receiveShadow
            position={[0, 6.52, 0]}
          />
        </group>
        <group name="Big Plant 2" position={[-163, -97, -194]}>
          <group name="Stand" position={[0, -61, 0]} rotation={[0, Math.PI / 4, 0]} scale={1.63}>
            <mesh
              name="Wood4"
              geometry={nodes.Wood4.geometry}
              material={materials['Wood4 Material']}
              position={[0, 0, 0]}
              rotation={[0, -Math.PI / 4, 0]}
              scale={0.61}
            />
          </group>
          <group name="Plant 2" position={[-1, 7, -1]} rotation={[0, 1.08, 0]} scale={0.72}>
            <mesh
              name="Plant 2 Leaves"
              geometry={nodes['Plant 2 Leaves'].geometry}
              material={materials['Plant 2 Leaves Material']}
              position={[9.61, 47.23, -3.87]}
              rotation={[0, -1.08, 0]}
              scale={1.4}
            />
            <mesh
              name="Earth"
              geometry={nodes.Earth.geometry}
              material={materials.Earth}
              position={[0.29, 0.62, 0.45]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Plant 2 Pot"
              geometry={nodes['Plant 2 Pot'].geometry}
              material={materials['Plant 2 Pot Material']}
              position={[0, -25.74, 0]}
            />
          </group>
        </group>
        <group name="Big Plant" position={[252, -97, -194]}>
          <group name="Stand1" position={[0, -61, 0]} rotation={[0, Math.PI / 4, 0]} scale={1.63}>
            <mesh
              name="Wood5"
              geometry={nodes.Wood5.geometry}
              material={materials['Wood5 Material']}
              position={[0, 0, 0]}
              rotation={[0, -Math.PI / 4, 0]}
              scale={0.61}
            />
          </group>
          <group name="Plant 1" position={[-1, 7, -1]} rotation={[0, 1.08, 0]} scale={0.72}>
            <mesh
              name="Plant 1 Leaves"
              geometry={nodes['Plant 1 Leaves'].geometry}
              material={materials['Plant 1 Leaves Material']}
              position={[9.61, 47.23, -3.87]}
              rotation={[0, -1.08, 0]}
              scale={1.4}
            />
            <mesh
              name="Earth1"
              geometry={nodes.Earth1.geometry}
              material={materials.Earth}
              position={[0.29, 0.62, 0.45]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1}
            />
            <mesh
              name="Plant 1 Pot"
              geometry={nodes['Plant 1 Pot'].geometry}
              material={materials['Plant 1 Pot Material']}
              position={[0, -27.09, 0]}
              rotation={[0, 0, 0]}
              scale={1}
            />
          </group>
        </group>
        <group name="TV" position={[46, 31, -199]}>
          <mesh
            name="Screen1"
            geometry={nodes.Screen1.geometry}
            material={materials['Screen1 Material']}
            position={[0, 0, 3.5]}
          />
          <mesh
            name="Hover1"
            geometry={nodes.Hover1.geometry}
            material={materials['Hover1 Material']}
            position={[0, 0, 3.5]}
          />
          <mesh name="TV1" geometry={nodes.TV1.geometry} material={materials['TV1 Material']} position={[0, 0, -4.5]} />
        </group>
        <mesh
          name="Wood6"
          geometry={nodes.Wood6.geometry}
          material={materials['Wood6 Material']}
          castShadow
          position={[-152, 146.5, 55]}
        />
        <group name="Sakura2" position={[-336.17, -172.47, -187.49]} scale={2}>
          <mesh
            name="Sakura3"
            geometry={nodes.Sakura3.geometry}
            material={materials.Sakura}
            position={[6.32, 47.03, 2.06]}
          />
          <mesh
            name="Tree trunk1"
            geometry={nodes['Tree trunk1'].geometry}
            material={materials['Tree trunk1 Material']}
            position={[1.33, 28.57, 0.65]}
          />
          <mesh
            name="Rectangle2"
            geometry={nodes.Rectangle2.geometry}
            material={materials['Rectangle2 Material']}
            position={[0.09, 14.22, -0.48]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Pot2"
            geometry={nodes.Pot2.geometry}
            material={materials['Pot2 Material']}
            position={[0, 4.09, -0.28]}
          />
        </group>
        <group name="Tiles" position={[-151.5, -190.5, 55.5]}>
          <mesh
            name="Second Floor Tile"
            geometry={nodes['Second Floor Tile'].geometry}
            material={materials['Second Floor Tile Material']}
            receiveShadow
            position={[-300.5, 340.39, -60.5]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
          <mesh
            name="Wooden Wall Tile"
            geometry={nodes['Wooden Wall Tile'].geometry}
            material={materials['Wooden Wall Tile Material']}
            receiveShadow
            position={[198.5, 344.5, -280.31]}
          />
          <mesh
            name="Wooden Floor Tile"
            geometry={nodes['Wooden Floor Tile'].geometry}
            material={materials['Wooden Floor Tile Material']}
            receiveShadow
            position={[-0.31, 0.5, -0.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1}
          />
        </group>
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#e3e3e3" />
      </group>
    </>
  )
}
